spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  jwt:
    jwtSecret: igoApplication
    jwtExpirationMs: 86400000

org:
  mipams:
    provenance:
      demo:
        encSecret: "17bccfb498595c425c2833135315611f1abf1f58f507666f66761d43236bb384"
        encScheme: "AES-256"
        credentials_path: 
        provenance_path: 
        exiftool_path:
        working_dir:
        claim_generator: "Mipams Generator v1.0"