version: '3'
services:
  provenance-server:
    image: provenance-server:latest
    build:
      context: ../server/
    ports:
      - 8080:8080
    environment:
      spring_servlet_multipart_max-file-size: 128MB
      spring_servlet_multipart_max-request-size: 128MB
      spring_servlet_multipart_enabled: "true"
      org_mipams_provenance_demo_encSecret: "17bccfb498595c425c2833135315611f1abf1f58f507666f66761d43236bb384"
      org_mipams_provenance_demo_encScheme: "AES-256"
      org_mipams_provenance_demo_credentials_path: "/app/credentials"
      org_mipams_provenance_demo_exiftool_path: "/app/Image-ExifTool-12.76/exiftool"
      org_mipams_provenance_demo_provenance_path: "/app/generated"
      org_mipams_provenance_demo_claim_generator: "Mipams Generator v2.0"
      org_mipams_provenance_demo_working_dir: "/app/assets"
      org_mipams_provenance: "DEBUG"

  provenance-client:
    image: provenance-client:latest
    build:
      context: ../client/
    volumes:
      - '../client:/app'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - provenance-server
    stdin_open: true
  # authorization-service:
  #   image: authorization-service:latest
  #   ports:
  #     - 8083:8080